// components/Quote.vue
<template>
  <div class="h-36 w-80 p-4 flex flex-col bg-purple-400 rounded-xl shrink-0">
    <span ref="author" class="text-lg font-medium"> </span>
    <span ref="title" class="text-xs text-purple-700"> </span>
    <span class="mt-2 text-purple-950">
      <slot></slot>
    </span>
  </div>
</template>
<script lang="ts">
export default {
  props: {
    author: {
      type: String,
      default: "Someone",
    },
    title: {
      type: String,
      default: "",
    },
  },
  mounted() {
    this.$refs.author.textContent = this.author;
    this.$refs.title.textContent = this.title;
  },
};
</script>

// src/lib/components/Quote.svelte
<script lang="ts">
    // Attributes
	export let author: string;
	export let authorTitle: string;
	export let quote: string;
</script>

<div class="h-40 w-80 p-4 flex flex-col bg-purple-400 rounded-xl shrink-0">
	<span class="text-lg font-medium">{author}</span>
	<span class="text-xs text-purple-700">{authorTitle}</span>
	<span class="mt-2 text-purple-950">
		{quote}
	</span>
</div>
